<!DOCTYPE html>
<html lang="en">

<head>

    <?php $this->load->view('admin-dashboard/fragments/admin_head_code') ?>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <?php $this->load->view('admin-dashboard/fragments/admin_sidebar') ?>


        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <?php $this->load->view('admin-dashboard/fragments/admin_topnav') ?>



                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Admin Pins</h1>
                    <?php if ($this->session->flashdata('ordersuccess')) : ?>
                        <div class="alert alert-success">
                            <p class="mb-4"><?= $this->session->flashdata('ordersuccess') ?>.</p>
                        </div>
                    <?php else : ?>
                        <p class="mb-4">List of admin registration pin</p>
                    <?php endif; ?>
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 style="float: left;" class="m-0 font-weight-bold text-primary">Admin Authentication Pin</h6>
                            <a href="<?= base_url('admin/generate_pin') ?>" style="float: right;" class="btn btn-info pull-right"><i class="fa fa-key"> </i> Generate new pin</a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <?php if ($this->session->has_userdata('pinError')) : ?>
                                    <div class="alert alert-danger text-center">
                                        <?php echo $this->session->pinError;
                                        $this->session->unset_userdata('pinError');
                                        ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($this->session->has_userdata('pinMsg')) : ?>
                                    <div class="alert alert-success text-center">
                                        <?php echo $this->session->pinMsg;
                                        $this->session->unset_userdata('pinMsg');
                                        ?>
                                    </div>
                                <?php endif; ?>
                                <table class="table table-bordered dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Pin</th>
                                            <th>Generated By</th>
                                            <th>Used By</th>
                                            <th>Date Generated</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        <?php
                                        if (count((array) $pins) > 0) :
                                            foreach ($pins as $pin) : ?>
                                                <tr class="tr-shadow">
                                                    <td><?= $pin->pin ?></td>
                                                    <td><?= $pin->created_by ?></td>
                                                    <td><?= $pin->used_by ?></td>
                                                    <td><?= $pin->date_created ?></td>
                                                    <td>
                                                        <?php if ($pin->no_of_usage > 0) : ?>
                                                            <span class="badge badge-danger">USED</span>
                                                        <?php else : ?>
                                                            <span class="badge badge-success">AVAILABLE</span>
                                                        <?php endif ?>
                                                    </td>
                                                </tr>
                                                <tr class="spacer"></tr>
                                        <?php endforeach;
                                        endif;
                                        ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->


            <?php $this->load->view('admin-dashboard/fragments/admin_footer') ?>
        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->


    <?php $this->load->view('admin-dashboard/fragments/admin_scripts') ?>
    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function() {
            $('.dataTable').DataTable();
        });
    </script>
</body>

</html>